name: ssis
description: A Simple Student Information System Project

publish_to: 'none'
version: 0.4.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  dropdown_button2: ^2.1.0
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true